### ISSUE TITLE
Out of Gas

### ISSUE THREAD

**Issue by kivo360** [oraclize/ethereum-bridge#23]
Is there any way I can not run out of gas

**Comment by D-Nice** [comment]
If it's a private chain, you can increase the gas limit. However, an 'out of gas' error may indicate some exception in the code, you need to be more specific with what is happening in your case, such as environment and the contract code you may be trying.

**Comment by kivo360** [comment]
Hi @D-Nice ,

Thanks for replying so quickly. This is a testrpc chain. I'm running a `truffle test` to see if I can get Oraclize to work. The smart contract is below:

```javascript
pragma solidity ^0.4.2;
import "./oraclizeAPI.sol";

contract SimpleStorage is usingOraclize{
  function SimpleStorage() {
    // OAR = OraclizeAddrResolverI(0x0983c64806544e78612622c0a9d28feaeeb533e2);
  }
  
  uint storedData = 10;

  function set(uint x) {
    storedData = x;
  }

  function getRandomNumber() constant returns(bytes32){
    bytes32 number = oraclize_query("WolframAlpha", "random number between 0 and 100");
    return number;
  }

  function get() constant returns (uint) {
    return storedData;
  }
}

```

The test function I'm using looks like this;

```
var SimpleStorage = artifacts.require("./SimpleStorage.sol");
const Web3 = require('web3')
// Instantiate new web3 object pointing toward an Ethereum node.
let web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8546"))


contract('Oraclize', function(accounts) {
  it("Get a random number", function() {
    return SimpleStorage.deployed().then(function(instance) {
      console.log(accounts[0]);
      // console.log(web3.fromWei(web3.eth.getBalance(accounts[0]), 'ether').toNumber());
      return instance.getRandomNumber.call(accounts[0]);
    }).then(function(balance) {
      console.log(balance.valueOf())
      assert.equal(10000, 10000, "10000 wasn't in the first account");
    });
  });

});

```

**Comment by kivo360** [comment]
I have no idea why it's not working. Is it attaching to the public chain?

**Comment by kivo360** [comment]
Hey @D-Nice . It's working now. How do I extract values out of Oraclize?

**Comment by D-Nice** [comment]
You may wish to join our gitter channel https://gitter.im/oraclize/ethereum-api

In the meantime, also make sure you have looked over our documentation, as I can see you are missing the mandatory `__callback` function http://docs.oraclize.it/

In a moment I will see to edit this message and include the solution too.

**Comment by kivo360** [comment]
I will join. I made changes to the contract for the callback. I took some sample code from your repository. Here's what I have now:

```javascript

pragma solidity ^0.4.2;
import "./oraclizeAPI.sol";

contract SimpleStorage is usingOraclize{

  event newOraclizeQuery(string description);
  event newRandomNumber(string number);

  function SimpleStorage() {
    // OAR = OraclizeAddrResolverI(0x0983c64806544e78612622c0a9d28feaeeb533e2);
    update();
  }
  
  uint storedData = 10;
  string public number;


  function set(uint x) {
    storedData = x;
  }

  function __callback(bytes32 myid, string result) {
      if (msg.sender != oraclize_cbAddress()) throw;
      number = result;
      newRandomNumber(number);
      // do something with the temperature measure..
  }

  function getRandomNumber() constant returns(string){
    return number;
  }

  function get() constant returns (uint) {
    return storedData;
  }

  function update() payable {
        newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
        oraclize_query("WolframAlpha", "random number between 0 and 100");
    }

}


```

Now I'm getting compilation errors:

``` bash

Using network 'development'.

Compiling ./contracts/ExternalComputation.sol...
Compiling ./contracts/SimpleStorage.sol...
Compiling ./contracts/connectors/addressResolver.sol...
Compiling ./contracts/connectors/oraclizeConnector.sol...
Compiling ./contracts/lib-experimental/inlineDynamicHelper.lib.sol...
Compiling ./contracts/lib-experimental/oraclizeAPI.lib.sol...
Compiling ./contracts/oraclizeAPI.sol...
Compiling ./contracts/oraclizeAPI_0.4.sol...
5
5

/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/wrapper.js:48
        throw e;
        ^
abort(5) at Error
    at jsStackTrace (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19718)
    at stackTrace (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19901)
    at abort (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:19:15285)
    at Array.dXb (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:11:585101)
    at Array.tX (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:8:557453)
    at Array.eea (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:6:495332)
    at Object.wOb [as dynCall_ii] (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:11:540050)
    at invoke_ii (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:1:1275129)
    at Array.ixa (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:7:494308)
    at Object.bVb [as dynCall_viii] (/home/kevin/.npm-packages/lib/node_modules/truffle/node_modules/solc/soljson.js:11:57723
2)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

```

**Comment by D-Nice** [comment]
Your last code works fine on http://dapps.oraclize.it/browser-solidity/#version=soljson-v0.4.11+commit.68ef5810.js

It comes with an integrated Oraclize module.

It may be easier to test and prototype in that environment. The issue you seem to be having is more specific to truffle currently from what I see, which is out of our scope, but I can confirm Truffle + TestRPC + ethereum-bridge work together, I've personally used them, albeit with the previous Truffle v2 and not v3.

**Comment by kivo360** [comment]
Do I need to run Rostpen?

**Comment by D-Nice** [comment]
No, with the above browser-solidity link, I tested your code and it works fine. It just runs in the Javascript VM, but has the oraclize-bridge automatically integrated.

**Comment by D-Nice** [comment]
Issue being closed as it appears your issue is resolved!
