### ISSUE TITLE
TypeError: Web3 is not a constructor

### ISSUE THREAD

**Issue by r-a-x** [oraclize/ethereum-bridge#34]
git clone git clone https://github.com/oraclize/ethereum-bridge.git
cd ethereum-bridge
node bridge -H localhost:8545 -a 9 --dev --disable-price

I am getting error 

/home/rahulb/ethereum-bridge/lib/bridge-util.js:8
const web3 = new Web3()
             ^

TypeError: Web3 is not a constructor
    at Object.<anonymous> (/home/rahulb/ethereum-bridge/lib/bridge-util.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rahulb/ethereum-bridge/bridge.js:6:18)
    at Module._compile (module.js:570:32)

**Comment by marcogiglio** [comment]
Hi @r-a-x , have you run `npm install` before?

**Comment by r-a-x** [comment]
@marcogiglio its hard to say, is there any way I can confirm that

**Comment by marcogiglio** [comment]
Probably not if you have this error. Just try to run it and see if it works?

**Comment by Medha08** [comment]
I ran into the same issue,solved it by deleting package-lock.json, node_modules and doing npm install again. See if it works for you

**Comment by D-Nice** [comment]
stale issue

**Comment by AfnanQureshi1** [comment]
getting same error! anyone resolved it?

**Comment by james-stevens** [comment]
```
#! /usr/bin/node

const myWeb3 = require("web3");
const web3 = new myWeb3("https://eth-mainnet.g.alchemy.com/v2/**************************");

web3.eth.ens.getContenthash("james.eth").then((result) => { console.log(result); });
```
gets....
```
const web3 = new myWeb3("https://eth-mainnet.g.alchemy.com/v2/I1iLOFKvcQ5NEt7GnYfmQDwXpYipWPaw");
             ^

TypeError: myWeb3 is not a constructor
    at Object.<anonymous> (/root/python/web3/web3.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

worked fine until I upgraded node from v16 to v18

Tried updating `web3`, tried removing it & reinstalling it - no luck

**Comment by Oguntoye** [comment]
@james-stevens and anyone who is having this issues

From Web3.js 4.x 

You should do this 
`const { Web3 } = require('web3'); `

Instead of doing this 
`const Web3 = require('web3');`

**Comment by james-stevens** [comment]
thanks @Oguntoye, I went with converting to module syntax
```
import { Web3 } from 'web3';
const web3 = new Web3("https://eth-mainnet.g.alchemy.com/v2/*****************");
```

I was just disappointed that code that had worked in node v16 then failed just by upgrading to node v18 - and **ALL** the tutorials I found online used to older syntax, that now doesn't work.

Getting anything working in web3 is hard enough - to then have it killed by an update was a killer.

**Comment by IsmaelTerreno** [comment]
> @james-stevens and anyone who is having this issues
> 
> From Web3.js 4.x
> 
> You should do this `const { Web3 } = require('web3'); `
> 
> Instead of doing this `const Web3 = require('web3');`

Same in my case I just change
`import {Web3} from "web3";`
to 
`import Web3 from "web3";`

Be careful because in the official docs we have :

```
import { Web3 } from 'web3'; // Bad way to import

const web3 = new Web3('https://eth.llamarpc.com');

const blockNumber = await web3.eth.getBlockNumber();
const chainId = await web3.eth.getChainId();
```
and it's not correct it should be 

```
import Web3  from 'web3'; // Correct way to import 

const web3 = new Web3('https://eth.llamarpc.com');

const blockNumber = await web3.eth.getBlockNumber();
const chainId = await web3.eth.getChainId();
```

So that works for me and I have "web3": "^4.16.0"

Thanks @Oguntoye  for the tip here.

Be careful on this bug where you can see it in the official dev docs in the date of this comment.

**Comment by james-stevens** [comment]
I actually now use the `id.js` library from Impervious - see my answer here, which includes a link to my code

https://stackoverflow.com/questions/76255558/getting-dns-data-from-ens-using-web3-py/78340783#78340783

**Comment by tkalinskov** [comment]
> Be careful because in the official docs we have :
> 
> ```
> import { Web3 } from 'web3'; // Bad way to import
> 
> const web3 = new Web3('https://eth.llamarpc.com');
> 
> const blockNumber = await web3.eth.getBlockNumber();
> const chainId = await web3.eth.getChainId();
> ```
> 
> and it's not correct it should be
> 
> ```
> import Web3  from 'web3'; // Correct way to import 
> 
> const web3 = new Web3('https://eth.llamarpc.com');
> 
> const blockNumber = await web3.eth.getBlockNumber();
> const chainId = await web3.eth.getChainId();
> ```

Tried both of these and somehow it doesn't work for my voting app. I also have Web3 4.16.0 and Node 22.11.0. That's how it looks in terminal:
```
var BigNumber = (new Web3()).toBigNumber(0).constructor;
                   ^

TypeError: Web3 is not a constructor
    at C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:27:20
    at Object.<anonymous> (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:803:3)
    at 1.ethjs-abi (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:805:4)
    at s (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:1:254)
    at C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:1:305
    at 2../contract.js (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:808:16)
    at s (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:1:254)
    at e (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:1:425)
    at Object.<anonymous> (C:\Users\Kalinskov_Timur\PycharmProjects\sidechainblockchain\src\js\truffle-contract.js:1:443)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)

Node.js v22.11.0
```
Any other fixes? Thanks in advance!
