### ISSUE TITLE
Error: More than one instance of bitcore-lib found.

### ISSUE THREAD

**Issue by louismerlin** [oraclize/ethereum-bridge#35]
After cloning the repo and running `npm install`, I try to `node bridge -H localhost:8545 -a 1` but this is what I get :
```
/home/louis/Adventures/Oraclize/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/louis/Adventures/Oraclize/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/louis/Adventures/Oraclize/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/louis/Adventures/Oraclize/ethereum-bridge/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
```
Also, running `npm find-dupes bitcore-lib` gives back
```
remove	inherits	2.0.1	node_modules/bitcore-lib/node_modules/inherits
```
I'll directly test my contracts on ropsten for the time being.

Thank you very much for this great service 👍

**Comment by D-Nice** [comment]
Some dependencies appear to have varying duplicate dependencies causing issues.

As a temporary workaround, I could provide you a `yarn.lock` file I use to install with yarn that avoids this dependency nightmare or you can wait for a proper fix.

**Comment by louismerlin** [comment]
This would be perfect, thank you ! You could make a gist fort example ?

**Comment by D-Nice** [comment]
It's been pushed into a separate branch [broken-dep-workaround](https://github.com/oraclize/ethereum-bridge/tree/broken-dep-workaround) branch.

**Comment by louismerlin** [comment]
It works ! Thanks 😄

**Comment by D-Nice** [comment]
master has been merged with the yarn workaround and an npm fix.
