### ISSUE TITLE
Unknown transaction

### ISSUE THREAD

**Issue by sivachaitanya** [oraclize/ethereum-bridge#37]
So I am running ethereum bridge inside a docker image, I did npm install and everything went fine until I ran node bridge command as follows, and alos I have unlocked my account. I have a private ethereum network setup and rpc is exposed over 8545, Following is the error log I am experiencing 

bash-4.4# node bridge -a 9
Please wait...
[2017-12-19T17:14:10.986Z] INFO you are running ethereum-bridge - version: 0.5.5
[2017-12-19T17:14:10.988Z] INFO saving logs to: ./bridge.log
[2017-12-19T17:14:10.990Z] INFO using active mode
[2017-12-19T17:14:10.991Z] INFO Connecting to eth node http://localhost:8545
[2017-12-19T17:14:12.919Z] INFO connected to node type Geth/v1.8.0-unstable-fe070ab5/linux-amd64/go1.9.2
[2017-12-19T17:14:13.513Z] WARN Using 0xb1d3073bcc45462a3b0dfe69902cdd12971efec9 to query contracts on your blockchain, make sure it is unlocked and do not use the same address to deploy your contracts
[2017-12-19T17:14:13.729Z] INFO deploying the oraclize connector contract...
Error: unknown transaction
    at Object.InvalidResponse (/root/oracle/ethereum-bridge/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/root/oracle/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as getTransactionReceipt] (/root/oracle/ethereum-bridge/node_modules/web3/lib/web3/method.js:145:58)
    at Timeout._onTimeout (/root/oracle/ethereum-bridge/lib/bridge-tx-manager.js:79:52)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Error: Error: unknown transaction
    at /root/oracle/ethereum-bridge/bridge.js:614:20
    at /root/oracle/ethereum-bridge/node_modules/async/dist/async.js:473:16
    at next (/root/oracle/ethereum-bridge/node_modules/async/dist/async.js:5315:29)
    at /root/oracle/ethereum-bridge/node_modules/async/dist/async.js:958:16
    at /root/oracle/ethereum-bridge/lib/bridge-core.js:274:21
    at Timeout.<anonymous> (/root/oracle/ethereum-bridge/lib/bridge-tx-manager.js:90:14)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

and after this is the log that is recorded in my geth - 

 Submitted contract creation              fullhash=0x3c49a20a7791a45ddbea222bd9df4bc6071388d678a06b2a5d3d58ae29e3cbc8 contract=0x41B0811e70D135540B0589bC578922995AdB167D

Not sure if this is the expected behavior ?

**Comment by marcogiglio** [comment]
Hi @sivachaitanya, it is not the expected behavior. I see that you are running with a development version of Geth, could you downgrade to a stable version and verify that the problem persist?

**Comment by sivachaitanya** [comment]
@marcogiglio  Thanks man, that helped I actually installed stable 1.7.3 geth version and able to deploy them now, Cheers !
![2017-12-20_11-30-38](https://user-images.githubusercontent.com/6172334/34193375-5b95a8b4-e579-11e7-8cdb-d1ac87e00a6d.png)
