### ISSUE TITLE
Why the callback in my private ethereum chain don't work?

### ISSUE THREAD

**Issue by oo7ww** [oraclize/ethereum-bridge#58]
OS: ubuntu 16.04
client: geth
I used the bridge on my private chain but it don't work, with no response to my contract calls. Here is the recent bridge.log record : 
```
{"level":"debug","message":"checking invalid __callback transactions","timestamp":"2018-05-24T09:37:01.726Z"}
[]
{"level":"debug","message":"reorg block target: 229","timestamp":"2018-05-24T09:37:02.451Z"}
{"level":"debug","message":"reorg block target: 229","timestamp":"2018-05-24T09:37:32.533Z"}
{"message":"reorgListen error","stack":"Error: Invalid JSON RPC response: undefined\n    at Object.InvalidResponse (/usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/errors.js:38:16)\n    at HttpProvider.send (/usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/httpprovider.js:91:22)\n    at RequestManager.send (/usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:58:32)\n    at Eth.get [as blockNumber] (/usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/property.js:107:62)\n    at Timeout._onTimeout (/usr/local/lib/node_modules/ethereum-bridge/bridge.js:801:50)\n    at ontimeout (timers.js:466:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:267:5)","level":"error","timestamp":"2018-05-24T09:37:32.608Z"}
{"level":"warn","message":"JSON RPC error, trying to re-connect every 30 seconds","timestamp":"2018-05-24T09:37:32.608Z"}
```
I has set the OAR bridge recommed, but there was no callback. 
Can someone point out the problem?

**Comment by D-Nice** [comment]
Could you provide some more of the previous lines from the log, preceding the above log entries?

**Comment by D-Nice** [comment]
Duplicate privatenet issue, refer to https://github.com/oraclize/ethereum-bridge/issues/73#issuecomment-488338183
