### ISSUE TITLE
oraclize report "exceeds block gas limit"

### ISSUE THREAD

**Issue by liuzhijun23** [oraclize/ethereum-bridge#59]
I run my ethereum private blockchain on the port 8100,and I unlock my accounts 0,and accounts 0 has 140 ether. I run the ethreum-bridge as follow:
sudo ethereum-bridge -H localhost:8100 -a 0
the console print as follows:
`Please wait...
[2018-05-31T03:00:26.610Z] INFO you are running ethereum-bridge - version: 0.6.0-beta.1
[2018-05-31T03:00:26.611Z] INFO saving logs to: ./bridge.log
[2018-05-31T03:00:26.611Z] INFO using active mode
[2018-05-31T03:00:26.611Z] INFO Connecting to eth node http://localhost:8100
[2018-05-31T03:00:28.258Z] INFO connected to node type Geth/v1.8.9-unstable-d6ed2f67/linux-amd64/go1.10.2
[2018-05-31T03:00:28.615Z] WARN Using 0xd7b4e8fc34f1e8727d9d1ded91b6981ed96e8422 to query contracts on your blockchain, make sure it is unlocked and do not use the same address to deploy your contracts
[2018-05-31T03:00:28.734Z] INFO deploying the oraclize connector contract...
Error: Error: exceeds block gas limit
    at /usr/local/lib/node_modules/ethereum-bridge/bridge.js:615:20
    at /usr/local/lib/node_modules/ethereum-bridge/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/ethereum-bridge/node_modules/async/dist/async.js:5329:29)
    at /usr/local/lib/node_modules/ethereum-bridge/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/ethereum-bridge/lib/bridge-core.js:274:21
    at Object.callback (/usr/local/lib/node_modules/ethereum-bridge/lib/bridge-tx-manager.js:66:21)
    at /usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/method.js:142:25
    at /usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/requestmanager.js:86:20
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/ethereum-bridge/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ethereum-bridge/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Please wait...
_Exiting...`_
I don't know why I get these errors.Someone can help me?

**Comment by D-Nice** [comment]
@liuzhijun23 What is the block gas limit of your blockchain? If it's over 3700000, it should work, I'm surprised if it's smaller. If it is smaller, you MAY be able to decrease it by passing the `--gas` flag, but of course, you can only go so much lower, your best bet is increasing the block gas limit of your private blockchain.

**Comment by D-Nice** [comment]
Duplicate privatenet issue, refer to https://github.com/oraclize/ethereum-bridge/issues/73#issuecomment-488338183
