### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by goodstemy** [oraclize/ethereum-bridge#63]
I'm try to execute broadcast via `ethereum-bridge --url http://localhost:8542 --broadcast --new` and getting error below:
```
ethereum-bridge --url http://localhost:8542 --broadcast --new
Please wait...
[2018-08-30T20:42:08.143Z] INFO you are running ethereum-bridge - version: 0.6.1
[2018-08-30T20:42:08.144Z] INFO saving logs to: ./bridge.log
Error: Error: Error: Keystore: Must include hdPathString in createVault inputs. Suggested alternatives are m/0'/0'/0' for previous lightwallet default, or m/44'/60'/0'/0 for BIP44 (used by Jaxx & MetaMask)
    at /Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/bridge.js:200:22
    at /Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/lib/bridge-util.js:39:21
    at Function.KeyStore.createVault (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/node_modules/eth-lightwallet/lib/keystore.js:98:12)
    at Object.generateNewAddress (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/lib/bridge-util.js:36:22)
    at Object.<anonymous> (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/bridge.js:199:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)

Please wait...
/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/lib/blockchain-interface.js:32
  this.mainNode = config.node.main || '127.0.0.1:8545'
                         ^

TypeError: Cannot read property 'node' of undefined
    at BlockchainInterface [as constructor] (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/lib/blockchain-interface.js:32:26)
    at singletonWrapper (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/node_modules/pragma-singleton/PragmaSingleton.js:61:16)
    at process.removeAllLogs (/Users/ivan/.nvm/versions/node/v10.5.0/lib/node_modules/ethereum-bridge/lib/bridge-log-manager.js:138:7)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:441:27)
```

**Comment by kyriediculous** [comment]
Ethereum-bridge does not use hardcode versioning. 
Apparently there must have been some changes to eth-lightwallet and `hdStringPath` and `seedPhrase` are now mandatory fields

> 
> keystore.createVault(options, callback)
> 
> This is the interface to create a new lightwallet keystore.
> Options
> 
>     password: (mandatory) A string used to encrypt the vault when serialized.
>     seedPhrase: (mandatory) A twelve-word mnemonic used to generate all accounts.
>     salt: (optional) The user may supply the salt used to encrypt & decrypt the vault, otherwise a random salt will be generated.
>     hdPathString (mandatory): The user must provide a BIP39 compliant HD Path String. Previously the default has been m/0'/0'/0', another popular one is the BIP44 path string m/44'/60'/0'/0.
> 


 I changed a few lines in `bridge-util.js` , it's not neat but it works for testing purposes. I'm afraid bridge-util.js will need a rewrite or fixed versioning. 

```
const generateNewAddress = function (keyFile, callback) {
  const password = process.env.PASSWORD
  const seed = ethWallet.keystore.generateRandomSeed()
  ethWallet.keystore.createVault({
    seedPhrase: seed,
    hdPathString: "m/0'/0'/0'",
    password: password
  }, function (err, ks) {
    if (err) return callback(new Error(err), null)
    ks.keyFromPassword(password, function (err, pwDerivedKey) {
      if (err) return callback(new Error(err), null)
      ks.generateNewAddress(pwDerivedKey, 1)
      const generatedAddress = ethUtil.addHexPrefix(ks.getAddresses()[0])
      var keyFileContent = ''
      fs.readFile(keyFile, function read (err, data) {
        if (err) {
          if (err.code === 'ENOENT') keyFileContent = ''
        }
        keyFileContent = data
        const privateKeyExported = ks.exportPrivateKey(generatedAddress, pwDerivedKey)
        var privateToSave = [privateKeyExported]
        var accountPosition = 0
        if (keyFileContent && keyFileContent.length > 0) {
          privateToSave = privateKeyExported
          var keyObj = JSON.parse(keyFileContent.toString())
          accountPosition = keyObj.length
          keyObj.push(privateToSave)
          privateToSave = keyObj
        }
        var contentToWrite = privateToSave
        fs.writeFile(keyFile, JSON.stringify(contentToWrite), function (err) {
          if (err) callback(new Error(err), null)
          callback(null, {'success': true, 'address': generatedAddress, 'account_position': accountPosition})
        })
      })
    })
  })
}
```

**Comment by D-Nice** [comment]
Thanks, we'll take a look at this again. Which node package manager are you using, as npm and yarn should not run into these issues with their lock files present?

**Comment by kyriediculous** [comment]
I used npm to install the module globally. I'm on a different laptop right now, I'll post my versions and package versions tomorrow.

**Comment by D-Nice** [comment]
yes, that is the issue, ethereum-bridge will currently only install properly with npm/yarn, however, a lot of us use pnpm internally as well, so we may look to add the appropriate shrinkwrap for it.

**Comment by D-Nice** [comment]
fixed as of PR https://github.com/oraclize/ethereum-bridge/pull/70
