### ISSUE TITLE
Error: More than one instance of bitcore-lib found.

### ISSUE THREAD

**Issue by yuhferng** [oraclize/ethereum-bridge#66]
During our local chain test, we find ethereum-bridge fail to build correctly (running on ubuntu 18.04 and build with "npm install"). It may be caused by some package dependencies change and it requires some fix.

When running "npm install", the output was:
npm WARN bitcore-mnemonic@1.7.0 requires a peer of bitcore-lib@^0.16.0 but none was installed.

When running "node bridge -H localhost:8545 -a 9 --dev", the output was:
/home/test/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/tmesis/code/ina/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/tmesis/code/ina/ethereum-bridge/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tmesis/code/ina/ethereum-bridge/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)

**Comment by D-Nice** [comment]
Thanks for reporting, we'll take a look, albeit if the package-lock file is present, this should not be an aissue

**Comment by D-Nice** [comment]
Which version of node are you using? Please ensure you use a recent one that supports package-lock or even give yarn a whirl. We may however be moving towards a npm/pnpm based package management solution, so yarn support may get dropped in the future.

**Comment by yuhferng** [comment]
node -v : v8.11.2
Thank you for the reply, now both "npm install" and "yarn install" works
